### ISSUE TITLE
Guardar y salir cierra la aplicación

### ISSUE THREAD

**Issue by RubensDieWeise** [Proyectos1-FDI-UCM/c2324-Grupo05#148]
Descripción
Al intentar usar la mecánica de guardar y salir para volver a cerrar el nivel (necesaria para la batería de pruebas del apartado 1) se cierra la aplicación.

Pasos
Abrir el menú.
Hacer clic en “Save and Exit”.

Vídeo
https://drive.google.com/file/d/1gocSDTCj87oYGFX_F7RXKhSpNPEve0Ga/view?usp=drive_link

**Comment by andreaGonzAnas** [comment]
El botón save and exit entonces cumple con su función. Este botón guarda la partida y cierra la aplicación. Es posible que la confusión se deba a que el jugador espera que el exit le lleve al menú inicial.
