### ISSUE TITLE
Tras recoger el huevo la pantalla se queda negra

### ISSUE THREAD

**Issue by RubensDieWeise** [Proyectos1-FDI-UCM/c2324-Grupo05#152]
Descripción
Al terminar el primer nivel la pantalla se queda negra más de 10 segundos antes de mostrar el mensaje de que hemos encontrado un huevo.
No me ha ocurrido esto al terminar otros niveles.

Pasos
Al final del primer nivel recoger el huevo.

Vídeo
https://drive.google.com/file/d/1Z3DEav7YiVF5MPifgYGXodrKsWGwEaFd/view?usp=drive_link

**Comment by andreaGonzAnas** [comment]
Se queda negra, ya que está cargando la cinemática.
